ssh:
  hostname: "172.205.192.202"
  username: ""
  password: ""
  token: ""
  services_dir: "services/"

telegram:
  token: "6991574106:AAHHGq3UXdvkdno6ifmY4OK7wfEw8X7hPss"
  chat_id: "-4207111775"

services:
  destructive_farm:
    git_repo: "https://github.com/DestructiveVoice/DestructiveFarm.git"
  packmate:
    git_repo: "https://gitlab.com/packmate/starter.git"
